import { GameMode } from '../context/GameSessionContext';

export type MobileGameStatus = 'playable' | 'in-development' | 'multiplayer-only';

export type MobileGameCategory =
  | 'all'
  | 'refleks'
  | 'spor'
  | 'yaris'
  | 'kelime'
  | 'bilgi'
  | 'sosyal'
  | 'zeka'
  | 'sans';

export interface MobileGameDefinition {
  id: string;
  title: string;
  description: string;
  category: MobileGameCategory;
  categoryLabel: string;
  supportedModes: GameMode[];
  status: MobileGameStatus;
  route?: string;
  iconName: string;
  color: string;
}

export const MOBILE_GAME_CATEGORIES: { id: MobileGameCategory; label: string }[] = [
  { id: 'all', label: 'Tümü' },
  { id: 'refleks', label: 'Hız ve Refleks' },
  { id: 'spor', label: 'Spor' },
  { id: 'yaris', label: 'Yarış' },
  { id: 'kelime', label: 'Kelime' },
  { id: 'bilgi', label: 'Bilgi' },
  { id: 'sosyal', label: 'Sosyal' },
  { id: 'zeka', label: 'Zekâ ve Denge' },
  { id: 'sans', label: 'Şans ve Strateji' },
];

export const MOBILE_GAME_REGISTRY: MobileGameDefinition[] = [
  {
    id: 'target-hunt',
    title: 'Hedef Avı',
    description: 'Ekranda beliren hedeflere hızlıca dokun, isabet serini koru ve puanları topla!',
    category: 'refleks',
    categoryLabel: 'Hız ve Refleks',
    supportedModes: ['single', 'multiplayer'],
    status: 'playable',
    route: '/games/target-hunt',
    iconName: 'Zap',
    color: '#38BDF8',
  },
  {
    id: 'car-race',
    title: 'Mini Araba Yarışı',
    description: 'Otoyolda engellerden kaç, yakın geçişlerle ekstra skor kazan!',
    category: 'yaris',
    categoryLabel: 'Yarış',
    supportedModes: ['single', 'multiplayer'],
    status: 'in-development',
    iconName: 'Car',
    color: '#F59E0B',
  },
  {
    id: 'penalty',
    title: 'Penaltı Yarışması',
    description: 'Topa falso ver, kaleciyi ters köşeye yatır ve golleri sırala!',
    category: 'spor',
    categoryLabel: 'Spor',
    supportedModes: ['single', 'multiplayer'],
    status: 'in-development',
    iconName: 'Goal',
    color: '#10B981',
  },
  {
    id: 'basketball',
    title: 'Basket Atışı',
    description: 'Panyalı veya çizgi basketleri atarak seriler yakala!',
    category: 'spor',
    categoryLabel: 'Spor',
    supportedModes: ['single', 'multiplayer'],
    status: 'in-development',
    iconName: 'Target',
    color: '#F97316',
  },
  {
    id: 'archery',
    title: 'Okçuluk',
    description: 'Rüzgâr hızını ve açısını hesapla, tam 10 puanlık merkeze vur!',
    category: 'spor',
    categoryLabel: 'Spor',
    supportedModes: ['single', 'multiplayer'],
    status: 'in-development',
    iconName: 'Crosshair',
    color: '#EF4444',
  },
  {
    id: 'reflex',
    title: 'Refleks Düellosu',
    description: 'Işık yandığı anda rakibinden hızlı dokun, düelloyu kazan!',
    category: 'refleks',
    categoryLabel: 'Hız ve Refleks',
    supportedModes: ['single', 'multiplayer'],
    status: 'in-development',
    iconName: 'Activity',
    color: '#06B6D4',
  },
  {
    id: 'tug-of-war',
    title: 'Halat Çekme',
    description: 'Cihazın kendi tarafına en hızlı dokunan oyuncu halatı çeker!',
    category: 'spor',
    categoryLabel: 'Spor',
    supportedModes: ['multiplayer'],
    status: 'in-development',
    iconName: 'Swords',
    color: '#8B5CF6',
  },
  {
    id: 'tabu',
    title: 'Tabu',
    description: 'Yasaklı kelimeleri kullanmadan arkadaşlarına gizli kelimeyi anlat!',
    category: 'kelime',
    categoryLabel: 'Kelime',
    supportedModes: ['multiplayer'],
    status: 'in-development',
    iconName: 'MessageSquare',
    color: '#EC4899',
  },
  {
    id: 'hangman',
    title: 'Kelimeyi Kurtar',
    description: 'Yanlış tahmin hakların bitmeden gizli kelimeyi harf harf çöz!',
    category: 'kelime',
    categoryLabel: 'Kelime',
    supportedModes: ['single', 'multiplayer'],
    status: 'in-development',
    iconName: 'HelpCircle',
    color: '#A855F7',
  },
  {
    id: 'word-search',
    title: 'Kelime Avı',
    description: 'Harf tablosu içinde gizlenmiş kelimeleri en hızlı sen bul!',
    category: 'kelime',
    categoryLabel: 'Kelime',
    supportedModes: ['single', 'multiplayer'],
    status: 'in-development',
    iconName: 'Search',
    color: '#14B8A6',
  },
  {
    id: 'anagram',
    title: 'Karışık Harfler',
    description: 'Karıştırılmış harflerden en fazla anlamlı kelimeyi türet!',
    category: 'kelime',
    categoryLabel: 'Kelime',
    supportedModes: ['single', 'multiplayer'],
    status: 'in-development',
    iconName: 'Shuffle',
    color: '#F43F5E',
  },
  {
    id: 'forbidden-letter',
    title: 'Yasak Harf',
    description: 'Belirlenen yasak harfi kullanmadan en uzun cümleyi kur!',
    category: 'kelime',
    categoryLabel: 'Kelime',
    supportedModes: ['single', 'multiplayer'],
    status: 'in-development',
    iconName: 'Ban',
    color: '#EAB308',
  },
  {
    id: 'word-chain',
    title: 'Kelime Zinciri',
    description: 'Bir önceki kelimenin son harfiyle başlayan yeni kelime söyle!',
    category: 'kelime',
    categoryLabel: 'Kelime',
    supportedModes: ['single', 'multiplayer'],
    status: 'in-development',
    iconName: 'Link',
    color: '#6366F1',
  },
  {
    id: 'quiz-classic',
    title: 'Bilgi Yarışması',
    description: 'Genel kültür, tarih, bilim ve spor sorularında bilgini yarıştır!',
    category: 'bilgi',
    categoryLabel: 'Bilgi',
    supportedModes: ['single', 'multiplayer'],
    status: 'in-development',
    iconName: 'BookOpen',
    color: '#3B82F6',
  },
  {
    id: 'box-deal',
    title: 'Kutunu Seç',
    description: 'Kutuları tek tek aç, büyük ödüle ulaşmak için risk al!',
    category: 'sans',
    categoryLabel: 'Şans ve Strateji',
    supportedModes: ['single', 'multiplayer'],
    status: 'in-development',
    iconName: 'Gift',
    color: '#F59E0B',
  },
  {
    id: 'tower',
    title: 'Denge Kulesi',
    description: 'Sallanan kule bloklarını tam üst üste dizerek göğe yüksel!',
    category: 'zeka',
    categoryLabel: 'Zekâ ve Denge',
    supportedModes: ['single', 'multiplayer'],
    status: 'in-development',
    iconName: 'Layers',
    color: '#10B981',
  },
  {
    id: 'maze',
    title: 'Labirent Kaçışı',
    description: 'Çıkış yolunu en kısa sürede bul ve labirentten kaç!',
    category: 'zeka',
    categoryLabel: 'Zekâ ve Denge',
    supportedModes: ['single', 'multiplayer'],
    status: 'in-development',
    iconName: 'Compass',
    color: '#06B6D4',
  },
  {
    id: 'memory',
    title: 'Hafıza Rotası',
    description: 'Yanıp sönen ışık ve ses dizilimini aklında tut ve tekrar et!',
    category: 'zeka',
    categoryLabel: 'Zekâ ve Denge',
    supportedModes: ['single', 'multiplayer'],
    status: 'in-development',
    iconName: 'Brain',
    color: '#8B5CF6',
  },
  {
    id: 'charades',
    title: 'Sessiz Sinema',
    description: 'Konuşmadan ve ses çıkarmadan ekrandaki kelimeyi hareketlerinle anlat!',
    category: 'sosyal',
    categoryLabel: 'Sosyal',
    supportedModes: ['multiplayer'],
    status: 'in-development',
    iconName: 'Film',
    color: '#EC4899',
  },
  {
    id: 'pass-the-bomb',
    title: 'Bomba Kimde',
    description: 'Kategoriye uygun cevabı söyle, hemen telefonu sıradakine ver!',
    category: 'sosyal',
    categoryLabel: 'Sosyal',
    supportedModes: ['multiplayer'],
    status: 'in-development',
    iconName: 'Flame',
    color: '#EF4444',
  },
  {
    id: 'order-up',
    title: 'Doğru Sıraya Koy',
    description: 'Tarih, coğrafya ve bilim olaylarını doğru kronolojik sıraya diz!',
    category: 'sosyal',
    categoryLabel: 'Sosyal',
    supportedModes: ['single', 'multiplayer'],
    status: 'in-development',
    iconName: 'ListOrdered',
    color: '#10B981',
  },
  {
    id: 'estimation',
    title: 'Hangisi Daha Yakın',
    description: 'Nüfus, mesafe ve boyut sorularında gerçek değere en yakın tahmini yap!',
    category: 'sosyal',
    categoryLabel: 'Sosyal',
    supportedModes: ['single', 'multiplayer'],
    status: 'in-development',
    iconName: 'Target',
    color: '#38BDF8',
  },
];
