import type { GameMetadata, GameType } from '../types/game';

export const GAME_REGISTRY: Record<GameType, GameMetadata> = {
  'box-deal': {
    id: 'box-deal',
    title: 'Kutunu Seç',
    description: '20 kutudan birini seç, teklifleri değerlendir veya kendi kutundaki büyük puanı kazan!',
    category: 'sans',
    categoryLabel: 'Şans & Strateji',
    typeLabel: 'Sırayla',
    icon: 'Gift',
    unit: 'puan',
    rules: [
      '20 kapalı kutudan 1 tanesini kişisel kutunuz olarak seçin (Kutunuz ayrı bir alanda kilitlenecektir).',
      'Turlar halinde kalan kutuları açarak puan tablosundan eleyin.',
      'Her turun sonunda sistemin yaptığı puan teklifini kabul edebilir veya "Devam Et" diyebilirsiniz.',
      'Son 2 kutu kaldığında kendi kutunuzu tutabilir veya kalan kutuyla değiştirebilirsiniz.',
    ],
    medals: {
      easy: { bronz: 10000, gümüş: 50000, altın: 150000 },
      normal: { bronz: 20000, gümüş: 75000, altın: 250000 },
      hard: { bronz: 30000, gümüş: 100000, altın: 500000 },
    },
  },
  'tap-rush': {
    id: 'tap-rush',
    title: 'Hedef Avı',
    description: 'Ekranda beliren hedefleri avla, tuzaklara basma ve seriyi koru!',
    category: 'refleks',
    categoryLabel: 'Hız & Refleks',
    typeLabel: 'Aynı Anda',
    icon: 'Zap',
    unit: 'puan',
    rules: [
      'Ekranın farklı noktalarında beliren hedeflere hızlıca dokunun.',
      'Altın hedefler ekstra +3 puan kazandırır.',
      'Kırmızı tuzak hedeflere dokunmak -2 puan düşürür ve serinizi sıfırlar!',
      'Ardışık isabetler x2, x3, x4 puan çarpanı kazandırır.',
    ],
    medals: {
      easy: { bronz: 15, gümüş: 30, altın: 45 },
      normal: { bronz: 25, gümüş: 50, altın: 75 },
      hard: { bronz: 40, gümüş: 70, altın: 100 },
    },
  },
  'car-race': {
    id: 'car-race',
    title: 'Mini Araba Yarışı',
    description: 'Piste çık, engellerden kaç, güçlendirmeleri topla ve en uzun mesafeye ulaş!',
    category: 'yaris',
    categoryLabel: 'Yarış',
    typeLabel: 'Aynı Anda',
    icon: 'Car',
    unit: 'metre',
    rules: [
      'Tek Oyunculu: 3 Can hakkınız vardır. Araçlar, koniler ve yağ birikintilerinden kaçın.',
      'Kalkan, Nitro ve Mıknatıs güçlendirmelerini yakalayarak avantaj elde edin.',
      'Yakınından geçtiğiniz araçlar yakın geçiş bonusu ve seri çarpanı verir.',
      'Çok Oyunculu: Gaz butonlarına seri dokunarak arabanızı hızlandırın.',
    ],
    medals: {
      easy: { bronz: 150, gümüş: 300, altın: 500 },
      normal: { bronz: 250, gümüş: 500, altın: 800 },
      hard: { bronz: 400, gümüş: 800, altın: 1200 },
    },
  },
  penalty: {
    id: 'penalty',
    title: 'Penaltı Yarışması',
    description: 'Topu kalede istediğin noktaya sürükleyip fırlat, kaleciyi avla!',
    category: 'spor',
    categoryLabel: 'Spor',
    typeLabel: 'Sırayla',
    icon: 'Goal',
    unit: 'gol',
    rules: [
      'Topa basıp kalede hedeflediğiniz köşeye doğru sürükleyin ve bırakın.',
      'Sürükleme yönü şut yönünü, sürükleme mesafesi şut gücünü belirler.',
      'Çok güçlü şutlar üstten avuta gidebilir, çok zayıf şutları kaleci kolayca yakalar.',
      '5 şut sonunda en çok gol atan kazanır.',
    ],
    medals: {
      easy: { bronz: 2, gümüş: 3, altın: 5 },
      normal: { bronz: 3, gümüş: 4, altın: 5 },
      hard: { bronz: 3, gümüş: 4, altın: 5 },
    },
  },
  basketball: {
    id: 'basketball',
    title: 'Basket Atışı',
    description: 'Topu geriye çekip potaya fırlat! Temiz ve uzak atışlarla seriyi katla.',
    category: 'spor',
    categoryLabel: 'Spor',
    typeLabel: 'Sırayla',
    icon: 'Dribble',
    unit: 'puan',
    rules: [
      'Topa tıklayıp geriye/aşağıya doğru sürükleyin, bıraktığınızda top fırlayacaktır.',
      'Sürüklerken beliren kesikli rota çizgisini kullanarak nişan alın.',
      'Sayı yalnızca top çemberden yukarıdan aşağı geçtiğinde verilir.',
      '2 sayılık ve 3 sayılık çizgi gerisinden atışlar mevcuttur.',
    ],
    medals: {
      easy: { bronz: 10, gümüş: 18, altın: 26 },
      normal: { bronz: 14, gümüş: 24, altın: 32 },
      hard: { bronz: 18, gümüş: 28, altın: 40 },
    },
  },
  archery: {
    id: 'archery',
    title: 'Okçuluk',
    description: 'Yatay ve dikey nişan al, rüzgârı hesapla, tam 10 puanlık merkeze vur!',
    category: 'spor',
    categoryLabel: 'Spor',
    typeLabel: 'Sırayla',
    icon: 'Target',
    unit: 'puan',
    rules: [
      'Nişangâhı sürükleyerek veya yön butonlarıyla hedef panosuna doğrultun.',
      'Yayı basılı tutarak güç toplayın ve doğru anda serbest bırakın.',
      'Ekrandaki rüzgâr oku okunuzu yana saptırabilir.',
      'Tam 10 puanlık merkez vuruşu ağır çekim ve bonus puan kazandırır.',
    ],
    medals: {
      easy: { bronz: 20, gümüş: 35, altın: 45 },
      normal: { bronz: 25, gümüş: 40, altın: 48 },
      hard: { bronz: 30, gümüş: 42, altın: 50 },
    },
  },
  reflex: {
    id: 'reflex',
    title: 'Refleks Düellosu',
    description: 'Yeşil ışık yandığı an ilk basan raundu kapar! Erken basan faul yapar.',
    category: 'refleks',
    categoryLabel: 'Hız & Refleks',
    typeLabel: 'Aynı Anda',
    icon: 'ZapFast',
    unit: 'ms',
    isLowerScoreBetter: true,
    rules: [
      'Ekran "BEKLE" uyarısındayken dokunmayın! Erken dokunmak fauldür.',
      'Rastgele süre sonra "BAS!" uyarısı çıktığı an alanınıza ilk dokunan olun.',
      'Tek oyunculu modda milisaniye (ms) cinsinden en hızlı tepki süreniz ölçülür.',
      '5 raund sonunda en çok raund kazanan şampiyon olur.',
    ],
    medals: {
      easy: { bronz: 400, gümüş: 300, altın: 220 },
      normal: { bronz: 350, gümüş: 260, altın: 190 },
      hard: { bronz: 300, gümüş: 220, altın: 160 },
    },
  },
  'tug-of-war': {
    id: 'tug-of-war',
    title: 'Halat Çekme',
    description: 'Takım butonuna seri dokun, halatı kendi tarafına çek!',
    category: 'refleks',
    categoryLabel: 'Hız & Refleks',
    typeLabel: 'Aynı Anda',
    icon: 'Swords',
    unit: 'puan',
    rules: [
      'Oyuncular 2 takıma ayrılır (1v1, 2v1, 2v2).',
      'Kendi alanınızdaki butona ritmik şekilde hızlıca dokunun.',
      'Basılı tutmak geçersizdir, tekil seri dokunuşlar halatı çeker.',
      'Halatı hedef sınırından öteye çeken takım yarışı kazanır.',
    ],
    medals: {
      easy: { bronz: 40, gümüş: 70, altın: 100 },
      normal: { bronz: 50, gümüş: 80, altın: 100 },
      hard: { bronz: 60, gümüş: 90, altın: 100 },
    },
  },
  'air-hockey': {
    id: 'air-hockey',
    title: 'Hava Hokeyi',
    description: 'Tokmağını sürükle, diski rakip kaleye gönder ve 5 gole ilk ulaşan ol!',
    category: 'spor',
    categoryLabel: 'Spor',
    typeLabel: 'Aynı Anda',
    icon: 'Disc',
    unit: 'gol',
    rules: [
      'Kendi yarı sahanızdaki tokmağı parmağınızla/fareyle sürükleyin.',
      'Diski hızlıca vurarak rakip kaleye sokmaya çalışın.',
      'Disk kenar duvarlardan ve tokmaklardan fiziksel olarak seker.',
      'İlk 5 gole ulaşan oyuncu kapışmayı kazanır.',
    ],
    medals: {
      easy: { bronz: 2, gümüş: 4, altın: 5 },
      normal: { bronz: 3, gümüş: 4, altın: 5 },
      hard: { bronz: 3, gümüş: 4, altın: 5 },
    },
  },
  tower: {
    id: 'tower',
    title: 'Denge Kulesi',
    description: 'Hareket eden blokları tam üst üste hizala! Taşan kısımlar kesilir.',
    category: 'zeka',
    categoryLabel: 'Zekâ & Denge',
    typeLabel: 'Sırayla',
    icon: 'Layers',
    unit: 'kat',
    rules: [
      'Ekran üstünde sağa sola kayan bloğu tam hizada durdurmak için dokunun.',
      'Hizadan taşan kısımlar bıçak gibi kesilir ve kule daralır.',
      'Tam hizada durdurmak "Mükemmel!" bonusu ve kule genişleme ödülü verir.',
      'Kule dengesini kaybedip blok tamamen boşa düşene kadar devam eder.',
    ],
    medals: {
      easy: { bronz: 8, gümüş: 15, altın: 25 },
      normal: { bronz: 12, gümüş: 22, altın: 35 },
      hard: { bronz: 16, gümüş: 30, altın: 45 },
    },
  },
  maze: {
    id: 'maze',
    title: 'Labirent Kaçışı',
    description: 'Karakterini duvarlara çarpmadan engeller arasından çıkışa ulaştır!',
    category: 'yaris',
    categoryLabel: 'Yarış',
    typeLabel: 'Sırayla',
    icon: 'Compass',
    unit: 'saniye',
    isLowerScoreBetter: true,
    rules: [
      'Karakterinizi başlangıç noktasından çıkış kapsülüne doğru sürükleyin.',
      'Labirent duvarlarına çarpmak +0.2 saniye süre cezası ekler.',
      'Anahtarları toplayarak kilitli kapıları açın.',
      'En kısa sürede labirenti tamamlayan oyuncu kazanır.',
    ],
    medals: {
      easy: { bronz: 30, gümüş: 20, altın: 12 },
      normal: { bronz: 25, gümüş: 16, altın: 10 },
      hard: { bronz: 20, gümüş: 14, altın: 8 },
    },
  },
  memory: {
    id: 'memory',
    title: 'Hafıza Rotası',
    description: 'Yanıp sönen renk dizisini aklında tut ve aynı sırayla tekrar et!',
    category: 'zeka',
    categoryLabel: 'Zekâ & Denge',
    typeLabel: 'Sırayla',
    icon: 'Brain',
    unit: 'adım',
    rules: [
      'Ekrandaki renkli butonlar sırayla yanıp sönecektir.',
      'Sırayı aklınızda tutun ve aynı butonlara doğru sırayla basın.',
      'Her başarılı turda diziye yeni bir adım eklenir.',
      'Yanlış butona basan elenir, en uzun hafıza serisine ulaşan kazanır.',
    ],
    medals: {
      easy: { bronz: 5, gümüş: 9, altın: 14 },
      normal: { bronz: 7, gümüş: 12, altın: 18 },
      hard: { bronz: 9, gümüş: 15, altın: 22 },
    },
  },
  tabu: {
    id: 'tabu',
    title: 'Tabu',
    description: 'Ana kelimeyi 5 yasak kelimeyi söylemeden arkadaşlarına anlat!',
    category: 'kelime',
    categoryLabel: 'Kelime Oyunları',
    typeLabel: 'Sırayla',
    icon: 'BookOpen',
    unit: 'puan',
    rules: [
      'Aktif oyuncu telefonu eline alır ve kartı yalnızca kendisi görür.',
      'Telefon el değiştirirken gizlilik ekranı gösterilir ("Hazırım" demeden kart açılmaz).',
      'Tur süresi 60 saniyedir.',
      'Doğru anlatım +1 puan, Tabu yapmak -1 puan düşürür.',
      '3 tur sonunda en yüksek puana ulaşan şampiyon olur.',
    ],
    medals: {
      easy: { bronz: 4, gümüş: 8, altın: 12 },
      normal: { bronz: 6, gümüş: 11, altın: 16 },
      hard: { bronz: 8, gümüş: 14, altın: 20 },
    },
  },
  hangman: {
    id: 'hangman',
    title: 'Kelimeyi Kurtar',
    description: 'Gizli kelimeyi robotun enerjisi tükenmeden harf harf tahmin et!',
    category: 'kelime',
    categoryLabel: 'Kelime Oyunları',
    typeLabel: 'Sırayla',
    icon: 'Bot',
    unit: 'kelime',
    rules: [
      'Türkçe klavyeden harf seçerek gizli kelimeyi açın.',
      'Her yanlış harf robotun pil enerjisini düşürür (en fazla 6 yanlış hakkı).',
      'İpucu kullanıldığında ipucu puanı düşer.',
      'Çok oyunculu modda bir oyuncu kelimeyi gizlice yazar, diğeri tahmin eder.',
    ],
    medals: {
      easy: { bronz: 3, gümüş: 6, altın: 10 },
      normal: { bronz: 5, gümüş: 9, altın: 14 },
      hard: { bronz: 7, gümüş: 12, altın: 18 },
    },
  },
  'word-search': {
    id: 'word-search',
    title: 'Kelime Avı',
    description: '8x8 harf tablosuna saklanmış gizli kelimeleri parmağınla sürükleyerek bul!',
    category: 'kelime',
    categoryLabel: 'Kelime Oyunları',
    typeLabel: 'Sırayla',
    icon: 'Search',
    unit: 'puan',
    rules: [
      '8x8 harf tablosunda gizlenmiş kelimelerin ilk harfinden son harfine sürükleyin.',
      'Kelimeler yatay, dikey, çapraz veya ters yerleştirilmiş olabilir.',
      'Doğru bulunan kelimeler kalıcı vurgulanır ve listede üzeri çizilir.',
      'İpucu butonu bir kelimenin ilk harfini parlatır.',
    ],
    medals: {
      easy: { bronz: 40, gümüş: 70, altın: 100 },
      normal: { bronz: 60, gümüş: 90, altın: 120 },
      hard: { bronz: 80, gümüş: 110, altın: 150 },
    },
  },
  anagram: {
    id: 'anagram',
    title: 'Karışık Harfler',
    description: 'Karışık verilen harf kartlarına sırayla dokunarak doğru kelimeyi kur!',
    category: 'kelime',
    categoryLabel: 'Kelime Oyunları',
    typeLabel: 'Sırayla',
    icon: 'Grid',
    unit: 'kelime',
    rules: [
      'Karışık harf kartlarına dokunarak üstteki boşlukları doldurun.',
      'Geri almak için seçtiğiniz harfe tekrar dokunun.',
      '"Kontrol Et" ile cevabı onaylayın.',
      '60 saniye içinde en fazla kelimeyi çözen kazanır.',
    ],
    medals: {
      easy: { bronz: 4, gümüş: 8, altın: 12 },
      normal: { bronz: 6, gümüş: 11, altın: 16 },
      hard: { bronz: 8, gümüş: 14, altın: 20 },
    },
  },
  'forbidden-letter': {
    id: 'forbidden-letter',
    title: 'Yasak Harf',
    description: 'İstenen kategoride bir kelime yaz ama belirtilen yasak harfi kullanma!',
    category: 'kelime',
    categoryLabel: 'Kelime Oyunları',
    typeLabel: 'Aynı Anda',
    icon: 'Ban',
    unit: 'doğru',
    rules: [
      'Verilen kategoriye uygun Türkçe bir kelime girin.',
      'Cevabınızın içinde EKRANDAKİ YASAK HARF KESİNLİKLE OLMAMALIDIR!',
      'Yasak harf içeren veya geçerli olmayan kelimeler kabul edilmez.',
      'Çok oyunculu modda 10 saniye içinde cevap veremeyen elenir.',
    ],
    medals: {
      easy: { bronz: 5, gümüş: 10, altın: 15 },
      normal: { bronz: 8, gümüş: 14, altın: 20 },
      hard: { bronz: 11, gümüş: 18, altın: 25 },
    },
  },
  'word-chain': {
    id: 'word-chain',
    title: 'Kelime Zinciri',
    description: 'Önceki kelimenin son harfiyle başlayan yeni geçerli bir Türkçe kelime yaz!',
    category: 'kelime',
    categoryLabel: 'Kelime Oyunları',
    typeLabel: 'Sırayla',
    icon: 'Link',
    unit: 'kelime',
    rules: [
      'Sistemin veya rakibinizin yazdığı kelimenin SON HARFİ ile başlayan yeni kelime yazın.',
      'Yazılan kelime yerel Türkçe sözlükte bulunmalıdır.',
      'Aynı oyun oturumunda kullanılmış kelimeler tekrar kullanılamaz.',
      'Çok oyunculu modda hata yapan oyuncu 1 can kaybeder (Toplam 3 can).',
    ],
    medals: {
      easy: { bronz: 5, gümüş: 10, altın: 15 },
      normal: { bronz: 8, gümüş: 14, altın: 20 },
      hard: { bronz: 12, gümüş: 18, altın: 26 },
    },
  },
  'quiz-classic': {
    id: 'quiz-classic',
    title: 'Bilgi Yarışması: Klasik',
    description: '15 farklı kategoride süreli ve jokerli 10 soruluk bilgi maratonu!',
    category: 'bilgi',
    categoryLabel: 'Bilgi Yarışması',
    typeLabel: 'Sırayla',
    icon: 'HelpCircle',
    unit: 'puan',
    rules: [
      '10 soru sorulur, her soru için 15 saniye verilir.',
      'Doğru cevap 100 puan + kalan süreye göre hız bonusu kazandırır.',
      '3 Özel Joker mevcuttur: %50:%50, Süre Dondurma (5s) ve Pas / Değiştir.',
      'Arka arkaya doğru cevaplar seri çarpanı kazandırır.',
    ],
    medals: {
      easy: { bronz: 600, gümüş: 1000, altın: 1400 },
      normal: { bronz: 800, gümüş: 1300, altın: 1800 },
      hard: { bronz: 1000, gümüş: 1600, altın: 2200 },
    },
  },
  'quiz-fast-finger': {
    id: 'quiz-fast-finger',
    title: 'Hızlı Parmak',
    description: 'Butonuna ilk basan cevabı seçsin! Yanlışta hak diğer oyunculara geçer.',
    category: 'bilgi',
    categoryLabel: 'Bilgi Yarışması',
    typeLabel: 'Aynı Anda',
    icon: 'Zap',
    unit: 'puan',
    rules: [
      'Soru ve şıklar ekrana gelir gelmez butonunuza ilk siz dokunun.',
      'Butona ilk basan oyuncuya cevap vermesi için 5 saniye verilir.',
      'Doğru cevap puan kazandırır; yanlış cevapta sıra diğer oyunculara açılır.',
    ],
    medals: {
      easy: { bronz: 500, gümüş: 900, altın: 1300 },
      normal: { bronz: 700, gümüş: 1200, altın: 1700 },
      hard: { bronz: 900, gümüş: 1500, altın: 2000 },
    },
  },
  'quiz-true-false': {
    id: 'quiz-true-false',
    title: 'Doğru mu, Yanlış mı?',
    description: 'Bilgi cümlesini oku, saniyeler içinde Doğru veya Yanlış seç!',
    category: 'bilgi',
    categoryLabel: 'Bilgi Yarışması',
    typeLabel: 'Sırayla',
    icon: 'HelpCircle',
    unit: 'puan',
    rules: [
      'Ekrana gelen cümlenin Doğru veya Yanlış olduğunu tahmin edin.',
      'Tek oyunculu modda 30 saniye içinde en yüksek puanı toplayın.',
      'Çok oyunculu modda seçimler gizli yapılır, sonuçlar birlikte açıklanır.',
    ],
    medals: {
      easy: { bronz: 500, gümüş: 900, altın: 1300 },
      normal: { bronz: 700, gümüş: 1200, altın: 1700 },
      hard: { bronz: 900, gümüş: 1500, altın: 2000 },
    },
  },
};

export function getGameMetadata(id: GameType): GameMetadata {
  return GAME_REGISTRY[id] || GAME_REGISTRY['tap-rush'];
}
